name: Auto Publish to NPM

on:
  push:
    branches: [main, master]
    paths-ignore:
      - "*.md"
      - "docs/**"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test # Si tienes tests

      - name: Build bundle
        run: yarn run bundle

      - name: Pack
        run: yarn pack

      - name: Determine version bump
        id: version
        run: |
          git log -1 --pretty=%B | grep -q "BREAKING CHANGE" && echo "bump=major" >> $GITHUB_OUTPUT || \
          git log -1 --pretty=%B | grep -q "feat:" && echo "bump=minor" >> $GITHUB_OUTPUT || \
          echo "bump=patch" >> $GITHUB_OUTPUT

      - name: Bump version
        run: |
          npm version ${{ steps.version.outputs.bump }} -m "chore(release): Bump version to %s [skip ci]"
          git push origin main --follow-tags

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
